export const playIconStyle = {
  position: "absolute",
  top: "50%",
  left: "50%",
  width: 40,
  height: 40,
  borderRadius: "50%",
  transform: "translate(-50%, -50%)",
  backgroundColor: "rgba(0, 0, 0, 0.5)",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  opacity: 0,
  transition: "opacity 0.3s ease",
  "&::before": {
    content: '""',
    display: "block",
    width: 0,
    height: 0,
    borderTop: "12px solid transparent",
    borderBottom: "12px solid transparent",
    borderLeft: "20px solid #fff",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-35%, -50%)",
  },
};
